version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - mkdir -p package
      - pip install -r requirements.txt -t package/
      - cp -r . package/
      - cd package
      - zip -r ../deployment_package.zip .
      - cd ..
